name: Test Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.8.0
      uses: actions/setup-node@v3.1.0
      with:
        node-version: '16.8.0'
        cache: 'npm'
    - name: Setup ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.2
        bundler-cache: true
    - name: Install Node Dependencies
      run: npm ci
    - name: Install iOS Pods
      run: |
        pod install --project-directory=ios
    - run: npm run ios
